### ISSUE TITLE
parentNode property ?

### ISSUE THREAD

**Issue by Chimrod** [dbuenzli/brr#10]
Hello, I'm opening the issue because I did not found how to I can declare/access [parentNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/parentNode) the property.

The type of the property should be `Brr.El.t Brr.El.Prop.t`, but there is no constructor with such signature (only the basic types are provided). Maybe is this causing cyclic references between `El` and `El.Prop` modules ? Is there an easy way to access to such properties ?

**Comment by dbuenzli** [comment]
I have no good answer for why it may be missing. Maybe (?) it's the belief that by only working in [one direction](https://erratique.ch/software/brr/doc/Brr/El/index.html#children) the DOM manipulations easier to understand. I don't have that in my head now but I'm not strictly against adding it.

> Is there an easy way to access to such properties ?

Yes remember that [El.t](https://erratique.ch/software/brr/doc/Brr/El/index.html#type-t) are DOM nodes. So for now simply get the FFI javascript object and lookup the property:

```ocaml
let parent_node e = El.of_jv (Jv.get (El.to_jv e) "parentNode")
```

Note `Brr.El.Prop.t` is rather designed for quick access to element specific props. For those many small elements which are not further typed than `El.t`.

**Comment by dbuenzli** [comment]
> ```ocaml
> let parent_node e = El.of_jv (Jv.get (El.to_jv e) "parentNode")
> ```

Well that of property can return `null` so that should rather be: 

```ocaml
let parent_node e = Jv.find_map El.of_jv (El.to_jv e) "parentNode"
```

**Comment by Chimrod** [comment]
I'm not completely satisfied with this solution : after thinking a bit on the problem, we should not see only this missing property, but a more general way to extends the existing API.

As you mentioned, "Exhaustiveness is a non-goal.", and brr should be open to the world wide without opening issue for each missing function (I think this is not interesting for you as maintener). (the functions `of_jv` and `to_jv` are a solution, but : 1. are not publically declared in the documentation, 2. are like an `Obj.magic` solution which is not really elegant)

The library already has a `Prop.t` type, with appropriate setter and getter functions, and this would more coherent to reuse this type for custom property. I'm much in favor of a `El.Prop.custom` function which allow to declare any type as a property, and let the typechecker ensure that the type is coherent.

I can propose a pull request for that, but I want to be sure that you are Ok with this design as it may duplicate the existing functions in the `El` module (which are already setters and getters to properties).

I whish you a Merry Christmas :)

**Comment by dbuenzli** [comment]
> I'm not completely satisfied with this solution : after thinking a bit on the problem, we should not see only this missing property, but a more general way to extends the existing API.
[...]
> As you mentioned, "Exhaustiveness is a non-goal.", and brr should be open to the world wide without opening issue for each missing function (I think this is not interesting for you as maintener).

That's what `M.{of,to}_jv` functions are for. They are precisely here so that the binding space remains extensible, for both El.t values themselves or other APIs using them. For example if you have an API that returns you DOM nodes you will have to use `El.of_jv`, if you have an API that consumes DOM nodes you will have to use `El.to_jv`. See the [FFI cookbook](https://erratique.ch/software/brr/doc/ffi_cookbook.html#iface_class) about that. 

> (the functions `of_jv` and `to_jv` are a solution, but : 1. are not publically declared in the documentation, 

On the same ground that, for example, `Bytes.unsafe_string` is not.

> 2. are like an `Obj.magic` solution which is not really elegant)
[...]
> I'm much in favor of a `El.Prop.custom` function which allow to declare any type as a property, and let the typechecker ensure that the type is coherent.

I think you are luring yourself here, the `Prop.t` is also an `Obj.magic` solution. You are not making things any better by using that, the type checker doesn't give you any form of better guarantee.

> The library already has a `Prop.t` type, with appropriate setter and getter functions, and this would more coherent to reuse this type for custom property. 

I don't want to push the `El.Prop` solution too much or now. You should rather see it as mecanism to extract basic data from DOM nodes. If that data is no longer basic then it's better to start making a type and associated module for the element kind. See for example [here](https://erratique.ch/software/brr/doc/Brr/El/index.html#ifaces). 

> I can propose a pull request for that, but I want to be sure that you are Ok with this design as it may duplicate the existing functions in the `El` module (which are already setters and getters to properties).

As you may now have inferred :-) I'm not Ok with this design. 

If you want to add `El.parent` and possibly `El.set_parent` to the API you are welcome. If not I will likely do it myself for the next release.
