### ISSUE TITLE
Would Ctypes-esque function creation for JavaScript FFI be possible?

### ISSUE THREAD

**Issue by Ilazki** [dbuenzli/brr#16]
This is a question and possibly a feature request because I don't know if it's actually possible to do.  I tried looking into it myself and got nowhere so I'm posting it here in case someone smarter than me can figure out if the idea's viable or not.

The idea was to create some kind of FFI function creation method for Brr similar to how [Ctypes](https://github.com/ocamllabs/ocaml-ctypes) allows you to programmatically define foreign functions entirely within OCaml.  To explain, with Ctypes you can define function signatures in a form like `string @-> int @-> returning void` and end up with a callable function with the appropriate number of arguments and correct function signature, handling the conversion of OCaml types for each argument as needed.

If possible, something like that could be useful in Brr as a cleaner alternative to writing wrapper functions that do things like `Jv.call js_fun [| Jv.of_string "foo"; Jv.of_int 42; Jv.of_string "bar" |]` by hand.  Instead, you'd do something like `my_fun = fn js_fun string @-> int @-> string` and get a curried function that has the appropriate conversions in place, allowing you to then write `my_fun "foo" 42 "bar"`.

This may be impossible to implement; I tried looking into how Ctypes works to see if it could be applied to Brr, but it uses powerful dark magics to do what it does, and I got completely lost trying to make sense of it. I really wanted to make it happen because the way Ctypes works is amazing;  Melange and Bucklescript make it easy to do something similar by using `external` to bind JS functions, so I thought it'd be nice to give Brr something similar by using a Ctypes-esque solution, but figuring out how Ctypes does its magic is beyond me.

**Comment by dbuenzli** [comment]
I think I may have tried at some point when I designed brr but I don't remember. One of the problem is that you'd need to make sure potential combinators do not start allocating too much closures and/or arrays to do their job. 

In the end what jsoo requires is a *fixed* sized OCaml array of js objects. From that perspective, my gut feeling is that this limits a bit the prospect of finding a set of efficient and usable combinators. 

If you want to discuss this I'd suggest you do so on the [OCaml forum](https://discuss.ocaml.org/).
