### ISSUE TITLE
`Uri`: `Params.of_jstr` can't correctly operate on the output of `Uri.query` or `Uri.fragment`

### ISSUE THREAD

**Issue by just-max** [dbuenzli/brr#50]
As pointed out in https://github.com/dbuenzli/brr/issues/47#issuecomment-1488032203, URLs and URL encoding is a zoo, so apologies in advance if I'm misunderstanding something here.

Background: the `Brr.Uri` API claims (emphasis added):

> [Params.t](https://ocaml.org/p/brr/0.0.5/doc/Brr/Uri/Params/index.html#type-t) values represent key-value parameters stored in strings as "k0=v0&k1=v1...". They can be constructed from any [Jstr.t](https://ocaml.org/p/brr/0.0.5/doc/Jstr/index.html#type-t). In particular it means **they can be used with an URI [fragment](https://ocaml.org/p/brr/0.0.5/doc/Brr/Uri/index.html#val-fragment) or [query](https://ocaml.org/p/brr/0.0.5/doc/Brr/Uri/index.html#val-query)**.

However, the output of `Uri.query` (or `Uri.fragment`) has already been percent-decoded. Using `Params.of_jstr` then percent-decodes a second time. That results in the following behaviour:

```ocaml
let double_decode x =
  Jstr.append (Jstr.v "https://example.com?x=") x
  |> Uri.of_jstr |> Result.get_ok
  |> Uri.query |> Uri.Params.of_jstr
  |> Uri.Params.find (Jstr.v "x") |> Option.get

let _ = [
  double_decode (Jstr.v "abc")   (* "abc", as expected *) ;
  double_decode (Jstr.v "%25")   (* "%", as expected *)   ;
  double_decode (Jstr.v "%2525") (* "%" !!! *)            ;
]
```

For comparison, by using JavaScript directly:

```js
const no_double_decode = x => new URL(`https://example.com?x=${x}`).searchParams.get("x");

[
  no_double_decode("abc"),  // "abc"
  no_double_decode("%25"),  // "%"
  no_double_decode("%2525") // "%25"
];
```

Taking a URL, grabbing its query parameter string, and using that to make a `Params` is directly encouraged by the API, but the last case here is wrong with `Brr`.

I don't see any way to get the correct behaviour either. Some things that *don't* work:

- Pass the raw query string to `Params.of_jstr`. This would work, but the API doesn't expose the raw query string.
- Re-encode the output of `Uri.query`. `Uri.query` uses `Uri.decode` to percent-decode the result, which means it leaves some `%`-escapes in the output. Re-encoding would however escape the `%` symbol in those escapes, rather than only percent-encoding the the characters that were percent-decoded (in other words, `encode` is not the inverse of `decode`).

The problem here is not that `Params.of_jstr` is wrong, but rather that `Brr.Uri` is trying to be overly helpful by returning percent-decoded strings. By https://url.spec.whatwg.org/#concept-urlencoded-parser parsing the query string means splitting on `&`, then on `=`, then by https://url.spec.whatwg.org/#percent-decode percent-decoding the resulting key/value pairs. But that needs to performed on the raw URL, not the decoded URL.

Realistically, this isn't the only case where the semantics of a URI component can no longer be fully captured after percent-decoding, so if I'm understanding correctly, adding raw (non-decoded) accessors to `Uri` is inevitable. That aside, having a `Uri.parameters : Uri.t -> Params.t` directly would also be nice.

**Comment by dbuenzli** [comment]
Yes, it seems that by trying to fix the mess I added even more mess. 

Basically in a well designed system you'd expect that the mechanism for escaping a particular query syntax (which is unspecified by the URI standard) would be layered on top of the mechanism used to escape URI components but they are not. So the model I tried to expose here is simply wrong.

A similar problem occurs with the `Uri.with_uri` which automatically percent encodes the given components.

**Comment by dbuenzli** [comment]
I started fixing things by adding `raw_{query,fragment}` and `Params.of_{query,fragment}` and changing `with_uri`'s label to `raw_{query,fragment}` but now I realize the same problem occurs with `path` which should either not percent decode or split on `/` and percent decode segments. Also not sure about `scheme` but likely the problem exists with `host` aswell. 

I'm starting to wonder whether I should not simply remove the automatic percent encoding and decoding everywhere without changing the names. This was a wrong idea: if I read correctly [here](https://datatracker.ietf.org/doc/html/rfc3986#section-2.4) basically you need the URI scheme to actually know when/where to percent decode. 

At that point either:

1. I simply deprecate `Uri` and make one to one bindings on `URL` rather than trying to fix things.
2. Simply remove the percent encoding/decoding everywhere from the module.

Tempted by 2. but that is a silent change for clients.

**Comment by just-max** [comment]
Yes, it looks like the raw accessors and setters would be needed everywhere.

The section of the RFC you linked to describes the issue exactly. Clearly the authors thought this through, but the result is not exactly intuitive.

I guess my thoughts on fixing this would be:

Since this is tricky to design correctly and the URL API in the browser is very much mature, I'm in favour of binding to it directly—with some additional OCaml goodies like `with_url` if possible :) I do like the "corrected" names (fragment, ...) though.

I'm also hesitant about (2). I suspect many clients already don't pay close attention here, and might just as well be magically fixed by removing the auto-encoding. But putting the fixed version in its own namespace would probably be less surprising to existing clients overall.

Thanks for taking the time to look into this and working on a fix!

**Comment by dbuenzli** [comment]
So that took longer than expected. 

> Clearly the authors thought this through, but the result is not exactly intuitive.

This means that you can't provide an API that liberates client from encoding duties which is a recipe for disasters – the resulting zoo, as you call it, and my own fuck up is a good witness of that.

> Since this is tricky to design correctly and the URL API in the browser is very much mature, I'm in favour of binding to it directly—with some additional OCaml goodies like with_url if possible :) I do like the "corrected" names (fragment, ...) though.

It may be mature but it's unhelpful. 

Especially if you are working across the client and server[^1], you generally get different terminology and results with respect to the (likely saner) URI abstraction you use on your server which for example is unlikely to include separators like `:`, `#` and `?` in the component accessor.

So before calling it a day an introduce a `Url` and `Url_search_params` modules mapping directly on browser functionality. I'm in favour of trying to "save" the `Uri` module to provide a better dev experience in the browser.

As such here's what I did in e394558: 

1. Remove the automatic percent encoding and decoding in `Uri` accessors and constructors.
2. Added `Uri.[with_]{query,fragment}_params` functions.
3. Added `Uri.[with_]path_segments` functions.
4. Tried to clarify the documentation.

If you have time to have a quick look at e394558 and the [new docs](https://erratique.ch/software/brr/doc/Brr/Uri/index.html) that would be most welcome.

A quick `git grep` over my code bases seems to indicate that this change will not affect me and in one case actually even improved the correctness: I was transferring a `path` from one URI to the other which could have broken in case segments had percent-encoded slashes. I hope it will be the same for others. 

[^1]: Aka the ridiculous "full stack" moniker. I see rubble not a stack.

**Comment by just-max** [comment]
> a recipe for disasters

A whole cookbook of disasters even ;)

I generally like the approach you've settled on. It contains direct access to the URI components, but provides high-level helpers where useful.

> If you have time to have a quick look at https://github.com/dbuenzli/brr/commit/e394558d32ceac5afeff34ec8637f861173c968b and the [new docs](https://erratique.ch/software/brr/doc/Brr/Uri/index.html)

I've reviewed the linked commit. There are still a couple of cases where I'm not convinced that the `Uri` API is doing the right thing.

**Comment by dbuenzli** [comment]
> I've reviewed the linked commit. There are still a couple of cases where I'm not convinced that the `Uri` API is doing the right thing.

Indeed. I read to much on what JavaScript was returning on my http URIs and didn't get some of the nuances – to my defense even MDN doesn't mention them :-) Thanks for your insights.

After a quick look I think I agree with all your comments. I'll get to them as soon as I'm over with resolving #41.

**Comment by dbuenzli** [comment]
> I've reviewed the linked commit. There are still a couple of cases where I'm not convinced that the `Uri` API is doing the right thing.

So in ca677e2cfbc062ff69d I tweaked path handling to support schemes that have no hierarchical schemes. For the other comments, as discussed, the URL API doesn't allow us to distinguish between an empty query (or fragment) and lack of query (or fragment), so I kept it as is. 

Waiting for you to be convinced by the resulting API to close this.

**Comment by just-max** [comment]
Thanks for going to the trouble of going into all the detail here. I never would've thought the rabbit hole went so deep...

One last comment on the commit, then I'm convinced :)

**Comment by dbuenzli** [comment]
> Thanks for going to the trouble of going into all the detail here.

Very much into doing the right thing now and forget about it forever. I have neither the URI nor the URL standards in the head at the moment so your comments are gold.

I first thought about using this proposal:

> "lie" and return a one-element list with the entire (opaque) path

It made sense to me to not try to cut through the opacity. But then you get surprised the day your opacity starts with a `/`. So I finally went with:

> "lie" and split the path anyway, but without dropping the first character.

It's nonsensical but at least is unsurprisingly non-sensical :-)
 
That's in c6e590c27bbb8aaa

**Comment by just-max** [comment]
that's almost elegant again. lgtm :>

**Comment by dbuenzli** [comment]
Thanks for you help! I'll make a release in the upcoming days.
